import localFont from "next/font/local";
import "@/styles/globals.css";

const geistSans = localFont({
	src: "../fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "../fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export const generateMetadata = async ({ params }: { params: Promise<{ lang: string }> }) => {
	const { lang } = await params;
	return {
		title: `NextJS i18n Template - ${lang.toUpperCase()}`,
		description: "Generated by Create Next App and i18next",
	};
}

export default async function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode, params: Promise<{ lang: string }>;
}>) {
	const { lang } = await params;
	return (
		<html lang={lang}>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				{children}
			</body>
		</html>
	);
}
